# Generated by Django 3.2 on 2022-06-08 08:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Morph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordname', models.CharField(max_length=500)),
                ('meaning', models.CharField(max_length=500, null=True)),
                ('parts_of_speech', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.IntegerField()),
                ('morph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphogical_analyzer.morph')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='tasks.task')),
            ],
        ),
        migrations.AddConstraint(
            model_name='morph',
            constraint=models.UniqueConstraint(fields=('wordname', 'parts_of_speech'), name='morph_unique_constraint'),
        ),
    ]
