# Generated by Django 3.2 on 2022-03-23 07:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Morph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordname', models.CharField(max_length=500)),
                ('meaning', models.CharField(max_length=500, null=True)),
                ('parts_of_speech', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file_path', models.CharField(max_length=100)),
                ('output_file_path', models.CharField(max_length=100, null=True)),
                ('async_result_id', models.UUIDField(default=uuid.uuid4, null=True)),
                ('status_detail', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.IntegerField()),
                ('morph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.morph')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
        migrations.AddConstraint(
            model_name='morph',
            constraint=models.UniqueConstraint(fields=('wordname', 'parts_of_speech'), name='morph_unique'),
        ),
    ]
