# Generated by Django 3.2 on 2022-06-08 07:41

from django.db import migrations


# 参考 https://selfs-ryo.com/detail/django_migrations_2
def update_morph_data(apps, schema_editor):
    """
    Morphモデルのデータマイグレーション
    tasks.models.Morphのデータをmorphogical_analyzer.modesl.Morphのデータへ移動
    """
    old_morph_model = apps.get_model('tasks', 'Morph')
    new_morph_model = apps.get_model('morphogical_analyzer', 'Morph')
    for old_morph in old_morph_model.objects.all():
        new_morph_model.objects.create(
            id=old_morph.id,
            wordname=old_morph.wordname,
            meaning=old_morph.meaning,
            parts_of_speech=old_morph.parts_of_speech,
        )


def reverse_morph_data(apps, schema_editor):
    """
    Morphモデルのデータロールバック
    morphogical_analyzer.modesl.Morphのデータをtasks.models.Morphのデータへ移動
    """
    old_morph_model = apps.get_model('tasks', 'Morph')
    new_morph_model = apps.get_model('morphogical_analyzer', 'Morph')
    for new_morph in new_morph_model.objects.all():
        old_morph_model.objects.create(
            id=new_morph.id, 
            wordname=new_morph.wordname,
            meaning=new_morph.meaning,
            parts_of_speech=new_morph.parts_of_speech
        )
    new_morph_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('morphogical_analyzer', '0001_initial'),
        ('tasks', '0001_initial')
    ]

    # データマイグレーション tasks.models -> morphogical_analyzer.modelsへ
    operations = [
        migrations.RunPython(
            code=update_morph_data,
            reverse_code=reverse_morph_data
        )
    ]

