# Generated by Django 3.2 on 2022-06-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20220608_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='morph',
        ),
        migrations.RemoveField(
            model_name='word',
            name='task',
        ),
        migrations.DeleteModel(
            name='Morph',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
